M48
; DRILL file {KiCad 7.0.8} date Sat Oct 28 23:27:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-28T23:27:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1024
%
G90
G05
T1
X4.23Y-4.64
X5.17Y-3.16
T2
X4.23Y-4.78
X5.32Y-3.16
T0
M30
